# -*- coding: utf-8 -*-
"""Hotel_booking_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gDzzWAbVMli0pvnVY_-AbGeyG7hkjK0n
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('/content/hotel_booking.csv')

df.shape

df.columns

df.info()

df.isnull().sum()

df.describe()

df.drop(['company','agent'],axis=1,inplace=True)
df.dropna(inplace=True)

df['adr'].plot(kind='box')

df= df[df['adr']<5000]

#df=df[['adr']]<5000

df.describe()

df['is_canceled'].value_counts(normalize=True)

plt.figure(figsize=(10,5))
plt.bar(['not cancelled','cancelled'],df['is_canceled'].value_counts())
plt.show()

df['hotel'].value_counts()

resort_hotel=df[df['hotel']=='Resort Hotel']
resort_hotel['is_canceled'].value_counts(normalize=True)

city_hotel=df[df['hotel']=='City Hotel']
city_hotel['is_canceled'].value_counts(normalize=True)

resort_hotel = resort_hotel.groupby('reservation_status_date')[['adr']].mean()
city_hotel=city_hotel.groupby('reservation_status_date')[['adr']].mean()

plt.figure(figsize=(10, 5))
plt.title('Average Daily Rate in City and Resort Hotels', fontsize=30)

# Correcting `lablel` to `label`
plt.plot(resort_hotel.index, resort_hotel['adr'], label='Resort Hotel')
plt.plot(city_hotel.index, city_hotel['adr'], label='City Hotel')

# Correcting `forntsize` to `fontsize`
plt.legend(fontsize=20)

plt.show()



# Convert 'reservation_status_date' to datetime format
df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'], errors='coerce')
# Ensure the 'month' column is correctly derived from 'reservation_status_date'
df['month'] = df['reservation_status_date'].dt.month

# Set up the figure
plt.figure(figsize=(10, 5))

# Create the count plot
ax1 = sns.countplot(x='month', hue='is_canceled', data=df)

# Adjust the legend to appear outside the plot
legend_labels, _ = ax1.get_legend_handles_labels()
ax1.legend(bbox_to_anchor=(1, 1), title='Is Canceled')  # Add a title to the legend for clarity

# Add a title to the plot
plt.title('Reservation Status per Month')

# Display the plot
plt.show()

plt.figure(figsize=(8,4))
ax1=sns.countplot(x='hotel', hue='is_canceled', data=df,palette= 'Blues')
legend_labels,_=ax1.get_legend_handles_labels()
ax1.legend(bbox_to_anchor=(1,1))
plt.title('Reservation status per Hotel')
plt.xlabel('Hotel')
plt.ylabel('Number of Reservations')
plt.show()

resort_hotel=df[df['hotel']=='Resort Hotel']
resort_hotel=resort_hotel['is_canceled'].value_counts(normalize=True)
resort_hotel

city_hotel=df[df['hotel']=='City Hotel']
city_hotel = city_hotel['is_canceled'].value_counts(normalize=True)
city_hotel

plt.figure(figsize=(15,8))
plt.title('ADR per month',fontsize=30)
sns.barplot(x='month',y='adr',data=df[df['is_canceled']==1].groupby('month')[['adr']].sum().reset_index())
plt.legend(fontsize=20)
plt.show()

canceled_data=df[df['is_canceled']==1]
top_10_country=canceled_data['country'].value_counts()[:10]

plt.figure(figsize=(8,8))
plt.pie(top_10_country,autopct='%.2f',labels=top_10_country.index)
plt.title('Top 10 countries with canceled reservations')
plt.show()

df['market_segment'].value_counts(normalize=True)

df['market_segment'].value_counts()

canceled_data['market_segment'].value_counts(normalize=True)

canceled_df_adr=canceled_data.groupby('reservation_status_date')[['adr']].mean()
canceled_df_adr.reset_index(inplace=True)
canceled_df_adr.sort_values('reservation_status_date',inplace=True)

not_canceled_data=df[df['is_canceled']==0]
not_canceled_df_adr=not_canceled_data.groupby('reservation_status_date')[['adr']].mean()
not_canceled_df_adr.reset_index(inplace=True)
not_canceled_df_adr.sort_values('reservation_status_date',inplace=True)

plt.figure(figsize=(20,6))
plt.title('Average Daily Rate')
plt.plot(not_canceled_df_adr['reservation_status_date'],not_canceled_df_adr['adr'],label='not Canceled')
plt.plot(canceled_df_adr['reservation_status_date'],canceled_df_adr['adr'],label='Canceled')
plt.legend()

canceled_df_adr=canceled_df_adr[(canceled_df_adr['reservation_status_date']>'2016') & (canceled_df_adr['reservation_status_date']<'2017-09')]
not_canceled_df_adr=not_canceled_df_adr[(not_canceled_df_adr['reservation_status_date']>'2016') & (not_canceled_df_adr['reservation_status_date']<'2017-09')]

plt.figure(figsize=(20,6))
plt.title('Average Daily Rate',fontsize=30)
plt.plot(not_canceled_df_adr['reservation_status_date'],not_canceled_df_adr['adr'],label='not Canceled')
plt.plot(canceled_df_adr['reservation_status_date'],canceled_df_adr['adr'],label='Canceled')
plt.legend()